### ISSUE TITLE
感兴趣加入soybean的生态吗？

### ISSUE THREAD

**Issue by Azir-11** [NHZEX/nxAdmin-soybean-admin#3]
注意到您好像在做一些基于soybean与naive ui增强的内容，请问感兴趣加入到soybean文档内的生态部分吗？

**Comment by NHZEX** [comment]
还没完成功能迁移与重构，而且没有时间写文档（还是用于私人项目），加上会怪尴尬的。

**Comment by Azir-11** [comment]
嗯嗯，那您有什么需要可以随时在各个交流群里或者在soybean的issue里联系我
